### ISSUE TITLE
Api_doc endpoints

### ISSUE THREAD

**Issue by idkjs** [jsthomas/sensors#1]
Hi @jsthomas!

Thanks for taking the time to teach with your blog post and repo. I was mostly in here for the docker postgres setup because I was having an issue running one. 

I would like to know if you generated the api_doc for the endpoints or if you hand wrote them. If generated, how did you do it.

Also, as you note, your project builds with ocaml@4.11.1. It does not build with 4.12.0. You might consider adding an `opam.lock` on here so it just runs. You can do that by running:

```sh 
opam lock -y .
```

**Comment by jsthomas** [comment]
I hand-wrote the `api_doc.md` file, unfortunately. It would be nice to generate this type of content from a tool, perhaps one that simply extracts the documentation from comments in the source code.

Good point about the `opam.lock` file, that's an oversight that I'll fix today.

**Comment by idkjs** [comment]
Thats to bad. I will have to investigate [insomnia-cli](https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso).

Thank you, sir.
